<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>MimesisRework.Loot</AssemblyName>
    <RootNamespace>MimesisTestMod.EnemyDropLoot</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\MimesisTestMod\EnemyDropLoot\**\*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <Reference Include="MelonLoader"><HintPath>$(MIMESIS_DIR)\MelonLoader\net35\MelonLoader.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(MIMESIS_DIR)\MIMESIS_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(MIMESIS_DIR)\MIMESIS_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Collections.Immutable"><HintPath>$(MIMESIS_DIR)\MIMESIS_Data\Managed\System.Collections.Immutable.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(MIMESIS_DIR)\MelonLoader\net35\0Harmony.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
